# 스프링부트 애플리케이션 프로파일 그룹 정의
spring:
  profiles:
    group:
      local: common, dev

---

spring:
  config:
    activate:
      # 프로파일 지정
      on-profile:
        - common
  # 애플리케이션 이름 설정
  application:
    name: going-project-v.1.0.0
  main:
    banner-mode: off  # 스프링부트 애플리케이션 구동시 출력되는 시작 배너 끄기
  # 웹 브라우저의 새로고침을 통해 변경된 화면단 적용을 위해 템플릿 경로와 캐시값 설정
  thymeleaf:
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false  # 개발 완료시 false → true 변경
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
      # 웹 브라우저의 캐시 시간 지정
      cache:
        period: 36000

mybatis:
  # 서버 구동시 마이바티스의 동작 제어를 위한 설정 값 세팅
  configuration:
    # 매퍼 네임스페이스 단위로 동작되는 캐시 비활성화
    cache-enabled: false
    # SQL 세션 객체마다 가지고 있는 로컬 캐시의 적용 범위를 STATEMENT로 설정
    local-cache-scope: STATEMENT
    # 지연 로딩 비활성화
    lazy-loading-enabled: false
    # 스네이크 케이스 → 카멜 케이스 변환
    map-underscore-to-camel-case: true
    # 조회되는 값이 널 값일 경우, 누락되는 문제를 방지하기 위해 setter() 또는 Map의 put() 호출
    call-setters-on-nulls: true
    # 마이바티스에서 값이 널 값인 파라미터 처리
    jdbc-type-for-null: NULL
  # 매핑을 위한 클래스의 이름을 작성시, 해당 클래스가 속한 패키지 명 생략
  type-aliases-package: com.bins.gopl.domain.**.dto
  # 마이바티스의 사용자 정의 타입 핸들러가 위치한 패키지를 지정하여, 값의 변환 수행시 해당 타입 핸들러가 적용되도록 설정
  type-handlers-package: com.bins.gopl.global.common.mybatis
  # 매퍼 XML 파일의 경로 설정
  mapper-locations:
    - classpath:mappers/**/*_mapper.xml
    - classpath:mappers/*_mapper.xml

# 서버 설정
server:
  port: 80  # 내장 톰캣 서버의 포트 번호 설정
  # HTTP 요청 및 응답의 인코딩 설정
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

---

spring:
  config:
    activate:
      # 프로파일 지정
      on-profile:
        - dev
  # 데이터베이스 연결 정보 설정
  datasource:
    url: jdbc:mariadb://localhost:3306/gopl_db?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: suihin
    password: tq5033
    driver-class-name: org.mariadb.jdbc.Driver

# 로깅 레벨 설정
logging:
  level:
    root: info
    web: info